name: Build Windows EXE

on:
  push:
    branches:
      - main # 当 push 到 main 分支时触发

jobs:
  build:
    runs-on: windows-latest # 使用 Windows 运行环境

    steps:
      # 1️⃣ 获取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 安装 Python 3.11
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4️⃣ 打包项目
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --add-data "assets;assets" main_app.py

      # 5️⃣ 上传打包结果
      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/main_app.exe
